config:
  credentials: []
  project_repos:
    github.com/ARGOeu-Metrics/argo-probe-fedcloud:
      branch: master
      repo: https://github.com/ARGOeu-Metrics/argo-probe-fedcloud
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu-Metrics/argo-probe-fedcloud git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-periwinkle-guppy.sh
        container: qc.acc_clammy-copper-tetra
  QC.Doc:
    repos:
      github.com/ARGOeu-Metrics/argo-probe-fedcloud find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-puce-bison.sh
        container: qc.doc_scanty-chestnut-camel
      github.com/ARGOeu-Metrics/argo-probe-fedcloud git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-ivory-kakapo.sh
        container: qc.doc_homey-indigo-dane
      github.com/ARGOeu-Metrics/argo-probe-fedcloud markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-chocolate-clam.sh
        container: qc.doc_lousy-pumpkin-kudu
  QC.Lic:
    repos:
      github.com/ARGOeu-Metrics/argo-probe-fedcloud licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ruby-coati.sh
        container: qc.lic_crabby-zucchini-wolf
  QC.Sec:
    repos:
      github.com/ARGOeu-Metrics/argo-probe-fedcloud bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cardinal-dane.sh
        container: qc.sec_gummy-mustard-newfoundland
  QC.Sty:
    repos:
      github.com/ARGOeu-Metrics/argo-probe-fedcloud flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-lavender-earwig.sh
        container: qc.sty_muggy-carmine-schnauzer
  QC.Uni:
    repos:
      github.com/ARGOeu-Metrics/argo-probe-fedcloud pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-mustard-avocet.sh
        container: qc.uni_stinky-ecru-fly
  QC.Ver:
    repos:
      github.com/ARGOeu-Metrics/argo-probe-fedcloud get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-ivory-whale.sh
        container: qc.ver_geeky-eggplant-dachshund
timeout: 5400
